# This is a basic workflow to help you get started with Actions
# Manually triggered Fri 12/02/2021 7:20PM.
name: Scheduled Data Gov

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# Update.
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# TRIGGER

on:
  push:
    branches: [ main ]
  schedule:
  - cron: "5 8 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  runDataUpdate:
    # The type of runner that the job will run on
    name: Run Data Update
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run Data Update
      uses: ./_action-update
      env:
        BRANCH_NAME: master
        BOT_USER: usnistgov
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
